// This file is generated by scripts/generate-ui-types.mjs from src/types.ts.
// Do not edit by hand.

export type SourceType =
  | 'plex'
  | 'emby'
  | 'jellyfin'
  | 'kodi'
  | 'player'
  | 'mpc'
  | 'mpv'
  | 'iina'
  | 'vlc'

export const SOURCE_TYPES: readonly SourceType[] = [
  'plex',
  'emby',
  'jellyfin',
  'kodi',
  'player',
  'mpc',
  'mpv',
  'iina',
  'vlc',
] as const

export const LOCAL_SOURCE_TYPES: readonly SourceType[] = [
  'player',
  'mpc',
  'mpv',
  'iina',
  'vlc',
] as const

export type LogLevel = 'debug' | 'info' | 'warn' | 'error'

export interface SourceConfig {
  type: SourceType
  enabled: boolean
  url: string
  token: string
  pollInterval: number
  userFilter: string[]
}

export interface AppConfig {
  myshowsToken: string
  myshowsUrl?: string
  scrobblePercent: number
  logLevel: LogLevel
  interceptOnly: boolean
  sources: SourceConfig[]
}

export interface AppConfigSnapshot extends AppConfig {
  /** True when the process was started with the `--intercept-only` CLI flag. */
  cliInterceptOnlyLocked: boolean
  /** Absolute path to the on-disk config file — shown in the raw config
   *  editor so the user knows which file to back up. */
  configPath: string
}

export type SourceErrorCode = 'auth' | 'network' | 'unreachable'

export type PlaybackAction = 'progress' | 'stopped'

export type PlaybackState = 'playing' | 'paused'

export interface MediaInfo {
  resolution: string | null
  hdr: string | null
  audioCodec: string | null
  audioChannels: number | null
  audioLanguage: string | null
  container: string | null
}

export interface ExternalIds {
  myshow?: number
  trakt?: number
  simkl?: number
  imdb?: string
  tmdb?: string
  tvdb?: string
  slug?: string
  anidb?: number
  mal?: number
  anilist?: number
  kitsu?: number
  shikimori?: number
  netflix?: string
  tvrage?: string
  hulu?: number
  crunchyroll?: number
  moviedb?: string
  zap2It?: string
  kinopoisk?: number
}

export interface NormalizedEvent {
  type: 'movie' | 'episode'
  /** Stable playback-session identifier supplied by the source adapter. */
  sessionId: string
  /** Show/movie-level external IDs. Legacy `*Id` fields are kept during migration. */
  ids: ExternalIds
  imdbId: string | null
  tmdbId: string | null
  tvdbId: string | null
  /** Episode-level external IDs (empty for movies or when unavailable). */
  episodeIds: ExternalIds
  /** Episode-level external IDs (null for movies or when unavailable) */
  episodeImdbId: string | null
  episodeTmdbId: string | null
  episodeTvdbId: string | null
  title: string
  originalTitle: string | null
  year: number | null
  showTitle: string | null
  showOriginalTitle: string | null
  season: number | null
  episode: number | null
  userRating: number | null
  /** Content rating (e.g. "TV-MA", "PG-13") */
  contentRating: string | null
  /** Runtime in minutes */
  runtimeMinutes: number | null
  duration: number | null
  viewOffset: number | null
  source: SourceType
  action: PlaybackAction
  state: PlaybackState
  /** Player app version (e.g. "5.94.1") */
  appVersion: string | null
  /** Media quality/format info */
  media: MediaInfo | null
  /** Dub/voiceover team extracted from filename (e.g. "AniDUB", "TEPES") */
  dubTeam: string | null
}

export interface NowPlayingEntry {
  key: string
  event: NormalizedEvent
  percent: number
  updatedAt: string
}

export interface ScrobbleEvent extends NormalizedEvent {
  timestamp: string
  status: 'success' | 'error' | 'skipped'
  error?: string
  /** True when this event was processed in intercept-only mode (not actually sent to MyShows). */
  intercept: boolean
}

export interface PollingLog {
  timestamp: string
  level: string
  message: string
  repeatCount?: number
}

export type WsMessage =
  | { type: 'event'; data: ScrobbleEvent }
  | { type: 'log'; data: PollingLog }
  | { type: 'nowPlaying'; data: NowPlayingEntry[] }
  | { type: 'sourceError'; data: { source: SourceType; error: string; code: SourceErrorCode } }
